[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "md2ltx"
version = "0.0.38"
description = "Convert Markdown (.md) files to PDF ..."
readme = "README.md"
requires-python = ">=3.10"

authors = [
  { name = "Ryan Gerard Wilson", email = "info@ryangerardwilson.com" }
]

# Dependencies needed during runtime
dependencies = [
  "tqdm"
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/ryangerardwilson/md2ltx"
Issues = "https://github.com/ryangerardwilson/md2ltx"

[project.entry-points."console_scripts"]
md2ltx = "md2ltx.main:main"

[tool.setuptools.packages.find]
where = ["src"]

